# Generated by Django 3.0.4 on 2020-04-27 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Baby',
        ),
    ]
